"""Add field 'brand' in products model

Revision ID: 4115e618dd17
Revises: bb21a4fd6935
Create Date: 2025-07-31 15:06:24.411247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4115e618dd17'
down_revision: Union[str, Sequence[str], None] = 'bb21a4fd6935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
