"""add column shipper_token in orders, add unique=True in sku products, add user_dni column in users and delete it from useraddress, rename user_contact to phone_number

Revision ID: 47e548175095
Revises: 
Create Date: 2025-07-22 09:11:41.939362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '47e548175095'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipper_token', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.add_column('user', sa.Column('user_dni', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_dni'])
    op.add_column('useraddress', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('useraddress_user_dni_key'), 'useraddress', type_='unique')
    op.create_unique_constraint(None, 'useraddress', ['phone_number'])
    op.drop_column('useraddress', 'user_contact')
    op.drop_column('useraddress', 'user_dni')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useraddress', sa.Column('user_dni', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('useraddress', sa.Column('user_contact', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'useraddress', type_='unique')
    op.create_unique_constraint(op.f('useraddress_user_dni_key'), 'useraddress', ['user_dni'], postgresql_nulls_not_distinct=False)
    op.drop_column('useraddress', 'phone_number')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_dni')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.drop_column('order', 'shipper_token')
    # ### end Alembic commands ###
