"""change shipper_contact to shipper_phone_number in shippers model

Revision ID: 5e093fbbfd77
Revises: 6781a5ece5ee
Create Date: 2025-07-29 11:07:37.990811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e093fbbfd77'
down_revision: Union[str, Sequence[str], None] = '6781a5ece5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE shipper RENAME COLUMN shipper_contact TO shipper_phone_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE shipper RENAME COLUMN shipper_phone_number TO shipper_contact")
    # ### end Alembic commands ###
