"""add unique constraint in ProductVariant

Revision ID: 6781a5ece5ee
Revises: 47e548175095
Create Date: 2025-07-22 11:10:34.463293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6781a5ece5ee'
down_revision: Union[str, Sequence[str], None] = '47e548175095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'productvariant', ['product_id', 'size', 'color'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productvariant', type_='unique')
    # ### end Alembic commands ###
